# Process Tracker - 生产环境告警配置示例

# === 告警配置 ===
alerts:
  enabled: true
  suppress_duration: 30  # 30分钟抑制期，避免告警风暴
  
  rules:
    # === 第一优先级：系统级监控（最重要！）===
    
    # 系统CPU使用率告警 ⭐⭐⭐ 必须配置
    - name: system_cpu_usage
      metric: system_cpu_percent   # 系统级CPU使用率
      threshold: 80                # 系统CPU > 80%
      duration: 300                # 持续5分钟
      channels: ["feishu"]
      enabled: true
    
    # 系统内存使用率告警 ⭐⭐⭐ 必须配置
    - name: system_memory_usage
      metric: system_memory_percent # 系统级内存使用率
      threshold: 85                 # 系统内存 > 85%
      duration: 300                 # 持续5分钟
      channels: ["feishu"]
      enabled: true
    
    # === 第二优先级：单进程异常监控 ===
    
    # 单个进程高CPU告警（使用max聚合）⭐⭐ 推荐
    - name: single_process_high_cpu
      metric: cpu_percent
      threshold: 95        # 任意进程CPU > 95%（设置高一点避免误报）
      duration: 300        # 持续5分钟
      aggregation: max     # 使用最大值，检测单个进程
      channels: ["feishu"]
      enabled: true
    
    # 系统整体高CPU告警（使用avg聚合）
    - name: system_avg_high_cpu
      metric: cpu_percent
      threshold: 50        # 平均CPU > 50%（说明整体负载高）
      duration: 300        # 持续5分钟
      aggregation: avg     # 使用平均值
      channels: ["feishu"]
      enabled: false       # 默认禁用，按需启用
    
    # 单个进程极高CPU告警（紧急）⭐ 推荐
    - name: critical_process_cpu
      metric: cpu_percent
      threshold: 95        # 任意进程CPU > 95%
      duration: 60         # 持续1分钟立即告警
      aggregation: max     # 使用最大值
      channels: ["feishu"]
      enabled: true
    
    # 单个进程高内存告警（使用max聚合）⭐⭐ 推荐
    - name: single_process_high_memory
      metric: memory_mb
      threshold: 5000      # 任意进程内存 > 5GB
      duration: 300        # 持续5分钟
      aggregation: max     # 使用最大值
      channels: ["feishu"]
      enabled: true
    
    # === 第三优先级：其他监控（可选）===
    
    # 系统总内存告警（使用sum聚合）
    - name: system_total_memory
      metric: memory_mb
      threshold: 20000     # 总内存 > 20GB
      duration: 300        # 持续5分钟
      aggregation: sum     # 使用总和
      channels: ["feishu"]
      enabled: false       # 默认禁用，按需启用
    
    # 单个进程极高内存告警（紧急）⭐ 推荐
    - name: critical_process_memory
      metric: memory_mb
      threshold: 5000      # 任意进程内存 > 5GB
      duration: 60         # 持续1分钟立即告警
      aggregation: max     # 使用最大值
      channels: ["feishu"]
      enabled: true

# === 通知器配置 ===
notifiers:
  # 飞书机器人
  feishu:
    webhook_url: "${WEBHOOK_URL}"  # 从环境变量读取
  
  # 钉钉机器人（可选）
  # dingtalk:
  #   webhook_url: "https://oapi.dingtalk.com/robot/send?access_token=YOUR_TOKEN"
  #   secret: "YOUR_SECRET"  # 如果启用了签名验证
  
  # 企业微信机器人（可选）
  # wechat:
  #   webhook_url: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=YOUR_KEY"

# === 存储配置 ===
storage:
  max_size_mb: 100     # 总存储限制 100MB
  keep_days: 7         # 保留7天数据

# === Web界面配置 ===
web:
  enabled: true        # 启用Web监控界面
  host: "0.0.0.0"      # 监听所有网络接口
  port: "18080"        # Web端口

# === 指标类型说明 ===
# 
# 1. 系统级指标（推荐默认使用）⭐⭐⭐
#    - system_cpu_percent: 系统CPU使用率百分比
#      计算公式：sum(所有进程CPU%) / CPU核心数
#      示例：72核系统，10个进程各50% CPU = 500/72 = 6.94%
#    
#    - system_memory_percent: 系统内存使用率百分比
#      计算公式：sum(所有进程内存MB) / 系统总内存MB * 100
#      示例：总内存300GB，当前用260GB = 86.67%
#    
#    优点：直观！就像top命令看到的系统整体使用率
#
# 2. 进程级指标（需配合aggregation使用）
#    - cpu_percent: 进程CPU使用率（可>100%，多核）
#    - memory_mb: 进程内存MB
#    
#    aggregation参数：
#    - max（最大值）: 检测单个进程异常
#    - avg（平均值）: 检测平均负载（很少用）
#    - sum（总和）: 检测总量（不如用system_xxx_percent直观）

# === 最佳实践 ===
# 1. 必须配置：system_cpu_percent 和 system_memory_percent
# 2. 建议配置：cpu_percent (max) 和 memory_mb (max) 检测单进程异常
# 3. 可选配置：针对特定服务的process过滤监控

# === 使用说明 ===
# 1. 设置环境变量:
#    export WEBHOOK_URL="https://open.feishu.cn/open-apis/bot/v2/hook/YOUR_TOKEN"
#
# 2. 测试告警通知:
#    ./process-tracker --config config-production.yaml test-alert
#
# 3. 启动监控:
#    ./process-tracker --config config-production.yaml start --web
#
# 4. 访问Web界面:
#    http://YOUR_SERVER_IP:18080
#
# 5. 查看状态:
#    ./process-tracker status
#
# 6. 停止监控:
#    ./process-tracker stop
